### ISSUE TITLE
Do i need to pay monthly for it to work?

### ISSUE THREAD

**Issue by CurlyFlow** [cbo100/dashcamtool#1]
So i dont own a blackvue currently, but im looking for a solution to automatic download videos from a dashcam.

In your description you say:
BlackVue App > Firmware Settings > Cloud > Turn on, and add your wifi SSID settings

Do  i need to pay anything to blackvue to use this wifi feature?

**Comment by cbo100** [comment]
sorry, this is really old and I didn't see this question.

In case it still matters, ss far as I know the features needed to download videos after wifi aren't behind a subscription paywall.

**Comment by CurlyFlow** [comment]
Thanks, yes it still matters. I dont know any other dashcams where this can be achived, Is it right that after enabling wifi, the camera will automatic connect to that wifi network?

**Comment by cbo100** [comment]
My one does, It's an older DR-900s. No idea if the new models are different in this regard.
